ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('politicadatos/', include('politicadatos.urls')),

    path('blog/', include('blog.urls')),

    path('servicios/', include('servicios.urls')),

    path('contacto/', include('contacto.urls')),

    path('tienda/', include('tienda.urls')),
    
    path('carro/', include('carro.urls')),
    
    path('autenticacion/', include('autenticacion.urls')),
    

    path('',include('ProyectoWebApp.urls')),
]

ProyectoWeb/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
   
    path('',views.blog, name="blog"),
    path('categoria/<int:categoria_id>/',views.categoria, name="categoria")
    
    ]

  

ProyectoWeb/carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [
   
   
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
   
    
]

ProyectoWeb/tienda/urls.py
from django.urls import path
from .import views



urlpatterns = [
    
    path('',views.tienda,name="tienda"),
    
    ]

ProyectoWeb/carro/models.py
from django.db import models

# Create your models here.

ProyectoWeb/tienda/models.py
from django.db import models
# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.TimeField(auto_now_add=True)
    updated=models.TimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"
    def __str__(self):
        return self.nombre

     
class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    descripcion=models.CharField(max_length=200)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.TimeField(auto_now_add=True)
    updated=models.TimeField(auto_now_add=True)


    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

ProyectoWeb/carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect

# Create your views here.
def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("tienda")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("tienda")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("tienda")

def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("tienda")

    

ProyectoWeb/tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
def tienda(request):
    productos=Producto.objects.all()

    return render(request,"tienda/tienda.html", {"productos":productos})

ProyectoWeb/tienda/templates/carro/widget.html
<table class="table table-bordered " style="color: white">

    <thead>
    <tr>
        <th colspan="3" class="text-center">
            Carro de compras 

        </th>
    
    </tr>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Suma</th>
    </tr>
    <tbody>
        {% if request.session.carro.items %}
            {% for key,value in request.session.carro.items %}
                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>

                        {{value.precio}} $

                    </td>

                </tr>


            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                <div class="alert alert-danger text-center">
                    Sin productos
                </div>

                </td>
            </tr>    
        {% endif %}
    
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro}} $,
            </td>
            

        <tr>
    <tr>
        <th colspan="3" class="text-center">
            <button type="button" class="btn btn-success btn-lg btn-block">Comprar       carrito</button>

        </th>
    
    </tr>    
    </tfoot>




    </thead> 





</table>